### ISSUE TITLE
sym and enter button not selectable/usable on Switch

### ISSUE THREAD

**Issue by ZornTaov** [vgmoose/vgedit#2]
The sym and enter buttons don't react to touch controls or to menuing through the keyboards using the dpad, which means you're unable to add in new lines or whatever characters are in sym to a file.

**Comment by vgmoose** [comment]
enter button, as well as deleting lines, added in https://github.com/vgmoose/vgedit/commit/d671e11c4af544389c0e83076d141949cd572e34

**Comment by lukazumi** [comment]
Do I need to compile from source to get this function? Seems like a big enough change to deserve a release no?

**Comment by vgmoose** [comment]
agreed, the keyboard is misaligned on master right now due to chesto changes– will try to fix and release an update sometime this week

[here are some builds](https://github.com/vgmoose/vgedit/files/3543737/vgedits.zip) (RPX and NRO) in the meantime (from `dependency_helper.sh` and `TARGET` env set to `wiiu` or `switch`, on Ubuntu)

**Comment by vgmoose** [comment]
With the new 2.0 update, the enter button touch problem is fixed, and the sym key has been removed in favor of a tab key and putting symbols in the caps mode
